name: Deploy WordPress to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

    - name: Configure VPS & Deploy WordPress
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.VPS_HOST }} << 'EOF'
        
        # Update system
        sudo apt update && sudo apt upgrade -y
        
        # Install LEMP Stack with PHP 8.3
        sudo add-apt-repository ppa:ondrej/php -y
        sudo apt update
        sudo apt install -y nginx mariadb-client php8.3 php8.3-fpm php8.3-mysql unzip curl git
        
        # Enable and start necessary services
        sudo systemctl enable --now nginx php8.3-fpm

        # Configure WordPress database connection to AWS RDS
        sudo mkdir -p /var/www/html/wordpress

        # Clone WordPress (if not already cloned)
        if [ ! -d "/var/www/html/wordpress/wp-content" ]; then
          cd /var/www/html
          sudo git clone https://github.com/yourusername/wordpress-deploy.git wordpress
        fi

        # Set proper ownership & permissions
        sudo chown -R www-data:www-data /var/www/html/wordpress
        sudo chmod -R 755 /var/www/html/wordpress
        
        # Configure wp-config.php with GitHub Secrets
        sudo cp /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php
        sudo sed -i "s/database_name_here/${{ secrets.DB_NAME }}/" /var/www/html/wordpress/wp-config.php
        sudo sed -i "s/username_here/${{ secrets.DB_USER }}/" /var/www/html/wordpress/wp-config.php
        sudo sed -i "s/password_here/${{ secrets.DB_PASSWORD }}/" /var/www/html/wordpress/wp-config.php
        sudo sed -i "s/localhost/${{ secrets.DB_HOST }}/" /var/www/html/wordpress/wp-config.php

        # Configure Nginx for WordPress
        sudo bash -c 'cat > /etc/nginx/sites-available/wordpress <<EOF2
        server {
            listen 80;
            server_name your_domain_or_ip;

            root /var/www/html/wordpress;
            index index.php index.html index.htm;

            location / {
                try_files \$uri \$uri/ /index.php?\$args;
            }

            location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/run/php/php8.3-fpm.sock;
                fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
                include fastcgi_params;
            }

            location ~ /\.ht {
                deny all;
            }
        }
        EOF2'

        # Enable and restart Nginx
        sudo ln -sf /etc/nginx/sites-available/wordpress /etc/nginx/sites-enabled/
        sudo nginx -t
        sudo systemctl restart nginx php8.3-fpm

        # Install SSL Certificate
        sudo apt install -y certbot python3-certbot-nginx
        sudo certbot --nginx -d your_domain_or_ip --non-interactive --agree-tos -m your-email@example.com

        # Set up auto-renewal for SSL
        (sudo crontab -l 2>/dev/null; echo "0 0 * * * certbot renew --quiet") | sudo crontab -

        # Pull latest changes from GitHub
        cd /var/www/html/wordpress
        sudo git pull origin main

        # Restart services to apply changes
        sudo systemctl restart nginx php8.3-fpm

        EOF
